### ISSUE TITLE
Error unlock of unlocked mutex

### ISSUE THREAD

**Issue by lewandowskim1988** [GoogleCloudPlatform/gcsfuse#2630]
I have an issue with one of my `CI` tests.
All tests are mounting `FUSE` volume in same directory and do some operations but only one is failing with error message that I don't know how to manage.

Error message from Kubernetes `events` of failing `pod`:

```
Normal   Killing      12m                kubelet            Stopping container gke-gcsfuse-sidecar
Warning  FailedMount  12m (x3 over 12m)  kubelet            MountVolume.SetUp failed for volume "gcs-fuse-csi-pv" : rpc error: code = Internal desc = gcsfuse failed with error: fatal error: sync: unlock of unlocked mutex

goroutine 16040 [running]:
sync.fatal({0x172a50c?, 0xc0008158d8?})
  /usr/local/go/src/runtime/panic.go:1007 +0x18
sync.(*Mutex).unlockSlow(0xc000aa3a88, 0xffffffff)
  /usr/local/go/src/sync/mutex.go:229 +0x35
sync.(*Mutex).Unlock(0xc000a00a80?)
  /usr/local/go/src/sync/mutex.go:223 +0x25
github.com/googlecloudplatform/gcsfuse/v2/internal/fs.(*fileSystem).lookUpLocalFileInode.func1()
  /go/gcsfuse/internal/fs/fs.go:984 +0x46
panic({0x13989c0?, 0xc000c8cdc0?})
  /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/googlecloudplatform/gcsfuse/v2/internal/fs/inode.NewFileName({{0x0, 0x0}, {0xc000120bd0, 0x22}}, {0x2897a50, 0x0})
  /go/gcsfuse/internal/fs/inode/name.go:58 +0x108
github.com/googlecloudplatform/gcsfuse/v2/internal/fs.(*fileSystem).lookUpLocalFileInode(0xc000469dc0, {0x7c8aadc39e40?, 0xc00088c390?}, {0x2897a50, 0x1?})
  /go/gcsfuse/internal/fs/fs.go:989 +0x150
github.com/googlecloudplatform/gcsfuse/v2/internal/fs.(*fileSystem).lookUpOrCreateChildInode(0xc000469dc0, {0x1c5e100, 0xc000c8b310}, {0x7c8aadc39e40, 0xc00088c390}, {0x2897a50, 0x1})
  /go/gcsfuse/internal/fs/fs.go:923 +0x66
github.com/googlecloudplatform/gcsfuse/v2/internal/fs.(*fileSystem).LookUpInode(0xc000469dc0, {0x1c5e0c8?, 0xc000ba59b0?}, 0xc0004e0e10)
  /go/gcsfuse/internal/fs/fs.go:1344 +0x146
github.com/googlecloudplatform/gcsfuse/v2/internal/fs/wrappers.(*errorMapping).LookUpInode(0xc000ab3f30, {0x1c5e0c8?, 0xc000ba59b0?}, 0x137b620?)
  /go/gcsfuse/internal/fs/wrappers/error_mapping.go:126 +0x69
github.com/googlecloudplatform/gcsfuse/v2/internal/fs/wrappers.(*monitoring).LookUpInode(0xc000ab3f40, {0x1c5e0c8, 0xc000ba59b0}, 0xc0004e0e10)
  /go/gcsfuse/internal/fs/wrappers/monitoring.go:156 +0x76
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc000ac8720, 0xc000d8a000, {0x1c5e0c8, 0xc000ba59b0}, {0x1361900?, 0xc0004e0e10})
  /tmp/build_gcsfuse_gopath3695249373/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20240607092844-7285af0d05b0/fuseutil/file_system.go:144 +0x203
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps in goroutine 56
  /tmp/build_gcsfuse_gopath3695249373/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20240607092844-7285af0d05b0/fuseutil/file_system.go:123 +0x1be

goroutine 1 [select, 3 minutes]:
github.com/jacobsa/fuse.(*MountedFileSystem).Join(0xc000adecc0, {0x1c5de28, 0x29cdfe0})
  /tmp/build_gcsfuse_gopath3695249373/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20240607092844-7285af0d05b0/mounted_file_system.go:46 +0x6f
github.com/googlecloudplatform/gcsfuse/v2/cmd.runCLIApp(0xc0006bc160)
  /go/gcsfuse/cmd/legacy_main.go:468 +0x1825
github.com/googlecloudplatform/gcsfuse/v2/cmd.run.func1(0x1?)
  /go/gcsfuse/cmd/legacy_main.go:488 +0x1c
github.com/urfave/cli.HandleAction({0x139c4c0?, 0xc0004cc070?}, 0xc000880fc0?)
  /tmp/build_gcsfuse_gopath3695249373/pkg/mod/github.com/urfave/cli@v1.22.15/app.go:526 +0x75
github.com/urfave/cli.(*App).Run(0xc000880fc0, {0xc000140000, 0x11, 0x12})
  /tmp/build_gcsfuse_gopath3695249373/pkg/mod/github.com/urfave/cli@v1.22.15/app.go:286 +0x79b
github.com/googlecloudplatform/gcsfuse/v2/cmd.run()
  /go/gcsfuse/cmd/legacy_main.go:492 +0xbb
github.com/googlecloudplatform/gcsfuse/v2/cmd.ExecuteLegacyMain()
  /go/gcsfuse/cmd/legacy_main.go:507 +0x2b
main.main()
  /go/gcsfuse/main.go:83 +0x13e

goroutine 13 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0004b8880)
  /tmp/build_gcsfuse_gopath3695249373/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x9f
created by go.opencensus.io/stats/view.init.0 in goroutine 1
  /tmp/build_gcsfuse_gopath3695249373/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x8d

goroutine 37 [chan receive, 3 minutes]:
github.com/googlecloudplatform/gcsfuse/v2/internal/perf.HandleCPUProfileSignals()
  /go/gcsfuse/internal/perf/cpu.go:58 +0x85
created by github.com/googlecloudplatform/gcsfuse/v2/cmd.ExecuteLegacyMain in goroutine 1
  /go/gcsfuse/cmd/legacy_main.go:503 +0x1a

goroutine 38 [chan receive, 3 minutes]:
github.com/googlecloudplatform/gcsfuse/v2/internal/perf.HandleMemoryProfileSignals()
  /go/gcsfuse/internal/perf/memory.go:67 +0x98
created by github.com/googlecloudplatform/gcsfuse/v2/cmd.ExecuteLegacyMain in goroutine 1
  /go/gcsfuse/cmd/legacy_main.go:504 +0x26

goroutine 49 [syscall, 3 minutes]:
os/signal.signal_recv()
  /usr/local/go/src/runtime/sigqueue.go:152 +0x29
os/signal.loop()
  /usr/local/go/src/os/signal/signal_unix.go:23 +0x13
created by os/signal.Notify.func1.1 in goroutine 37
  /usr/local/go/src/os/signal/signal.go:151 +0x1f

goroutine 88 [select, 3 minutes]:
github.com/googlecloudplatform/gcsfuse/v2/internal/gcsx.garbageCollect({0x1c5e100, 0xc0006de9b0}, {0x170da5d, 0xd}, {0x1c676f8, 0xc000ac86e0})
  /go/gcsfuse/internal/gcsx/garbage_collect.go:108 +0x106
created by github.com/googlecloudplatform/gcsfuse/v2/internal/gcsx.(*bucketManager).SetUpBucket in goroutine 1
  /go/gcsfuse/internal/gcsx/bucket_manager.go:238 +0x745

goroutine 56 [syscall]:
syscall.Syscall(0x0, 0x3, 0xc001884000, 0x101000)
  /usr/local/go/src/syscall/syscall_linux.go:69 +0x25
syscall.read(0xc000d82060?, {0xc001884000?, 0x10?, 0x10?})
  /usr/local/go/src/syscall/zsyscall_linux_amd64.go:736 +0x38
syscall.Read(...)
  /usr/local/go/src/syscall/syscall_unix.go:181
internal/poll.ignoringEINTRIO(...)
  /usr/local/go/src/internal/poll/fd_unix.go:736
internal/poll.(*FD).Read(0xc000d82060, {0xc001884000, 0x101000, 0x101000})
  /usr/local/go/src/internal/poll/fd_unix.go:160 +0x2ae
os.(*File).read(...)
  /usr/local/go/src/os/file_posix.go:29
os.(*File).Read(0xc000d86000, {0xc001884000?, 0x7c7e10?, 0x7c8aadaa9ea8?})
  /usr/local/go/src/os/file.go:118 +0x52
github.com/jacobsa/fuse/internal/buffer.(*InMessage).Init(0xc0011d9840, {0x1c3d9c0?, 0xc000d86000?})
  /tmp/build_gcsfuse_gopath3695249373/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20240607092844-7285af0d05b0/internal/buffer/in_message.go:85 +0x4c
github.com/jacobsa/fuse.(*Connection).readMessage(0xc000d8a000)
  /tmp/build_gcsfuse_gopath3695249373/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20240607092844-7285af0d05b0/connection.go:346 +0x45
github.com/jacobsa/fuse.(*Connection).ReadOp(0xc000d8a000)
  /tmp/build_gcsfuse_gopath3695249373/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20240607092844-7285af0d05b0/connection.go:405 +0x3c
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps(0xc000ac8720, 0xc000d8a000)
  /tmp/build_gcsfuse_gopath3695249373/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20240607092844-7285af0d05b0/fuseutil/file_system.go:106 +0x6b
github.com/jacobsa/fuse.Mount.func1()
  /tmp/build_gcsfuse_gopath3695249373/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20240607092844-7285af0d05b0/mount.go:93 +0x32
created by github.com/jacobsa/fuse.Mount in goroutine 1
  /tmp/build_gcsfuse_gopath3695249373/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20240607092844-7285af0d05b0/mount.go:92 +0x5b9

goroutine 57 [chan receive, 3 minutes]:
github.com/googlecloudplatform/gcsfuse/v2/cmd.registerSIGINTHandler.func1()
  /go/gcsfuse/cmd/legacy_main.go:66 +0x65
created by github.com/googlecloudplatform/gcsfuse/v2/cmd.registerSIGINTHandler in goroutine 1
  /go/gcsfuse/cmd/legacy_main.go:64 +0xbc

goroutine 1347 [IO wait]:
internal/poll.runtime_pollWait(0x7c8aaddc0c80, 0x72)
  /usr/local/go/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc000067080?, 0xc000552800?, 0x0)
  /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
  /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000067080, {0xc000552800, 0x4800, 0x4800})
  /usr/local/go/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc000067080, {0xc000552800?, 0x7c8aaddf5c98?, 0xc0000dbe48?})
  /usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc000d86360, {0xc000552800?, 0xc000472930?, 0x411d5b?})
  /usr/local/go/src/net/net.go:179 +0x45
crypto/tls.(*atLeastReader).Read(0xc0000dbe48, {0xc000552800?, 0x0?, 0xc0000dbe48?})
  /usr/local/go/src/crypto/tls/conn.go:806 +0x3b
bytes.(*Buffer).ReadFrom(0xc0001f1b30, {0x1c403a0, 0xc0000dbe48})
  /usr/local/go/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0001f1888, {0x1c3e720, 0xc000d86360}, 0xc000472978?)
  /usr/local/go/src/crypto/tls/conn.go:828 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc0001f1888, 0x0)
  /usr/local/go/src/crypto/tls/conn.go:626 +0x3cf
crypto/tls.(*Conn).readRecord(...)
  /usr/local/go/src/crypto/tls/conn.go:588
crypto/tls.(*Conn).Read(0xc0001f1888, {0xc000c72000, 0x1000, 0x8?})
  /usr/local/go/src/crypto/tls/conn.go:1370 +0x156
net/http.(*persistConn).Read(0xc000141440, {0xc000c72000?, 0xc000c461e0?, 0xc000472d38?})
  /usr/local/go/src/net/http/transport.go:1977 +0x4a
bufio.(*Reader).fill(0xc0006eb9e0)
  /usr/local/go/src/bufio/bufio.go:110 +0x103
bufio.(*Reader).Peek(0xc0006eb9e0, 0x1)
  /usr/local/go/src/bufio/bufio.go:148 +0x53
net/http.(*persistConn).readLoop(0xc000141440)
  /usr/local/go/src/net/http/transport.go:2141 +0x1b9
created by net/http.(*Transport).dialConn in goroutine 1271
  /usr/local/go/src/net/http/transport.go:1799 +0x152f

goroutine 1436 [IO wait]:
internal/poll.runtime_pollWait(0x7c8aaddc0a90, 0x72)
  /usr/local/go/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc000504f00?, 0xc000c4f300?, 0x0)
  /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
  /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000504f00, {0xc000c4f300, 0x1300, 0x1300})
  /usr/local/go/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc000504f00, {0xc000c4f300?, 0x7c8aadbf3c58?, 0xc001e864c8?})
  /usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc000d87110, {0xc000c4f300?, 0xc000027930?, 0x411d5b?})
  /usr/local/go/src/net/net.go:179 +0x45
crypto/tls.(*atLeastReader).Read(0xc001e864c8, {0xc000c4f300?, 0x0?, 0xc001e864c8?})
  /usr/local/go/src/crypto/tls/conn.go:806 +0x3b
bytes.(*Buffer).ReadFrom(0xc000926630, {0x1c403a0, 0xc001e864c8})
  /usr/local/go/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000926388, {0x1c3e720, 0xc000d87110}, 0xc000027978?)
  /usr/local/go/src/crypto/tls/conn.go:828 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc000926388, 0x0)
  /usr/local/go/src/crypto/tls/conn.go:626 +0x3cf
crypto/tls.(*Conn).readRecord(...)
  /usr/local/go/src/crypto/tls/conn.go:588
crypto/tls.(*Conn).Read(0xc000926388, {0xc000e76000, 0x1000, 0x8?})
  /usr/local/go/src/crypto/tls/conn.go:1370 +0x156
net/http.(*persistConn).Read(0xc0009a5e60, {0xc000e76000?, 0xc000c467e0?, 0xc000027d38?})
  /usr/local/go/src/net/http/transport.go:1977 +0x4a
bufio.(*Reader).fill(0xc000297c20)
  /usr/local/go/src/bufio/bufio.go:110 +0x103
bufio.(*Reader).Peek(0xc000297c20, 0x1)
  /usr/local/go/src/bufio/bufio.go:148 +0x53
net/http.(*persistConn).readLoop(0xc0009a5e60)
  /usr/local/go/src/net/http/transport.go:2141 +0x1b9
created by net/http.(*Transport).dialConn in goroutine 1307
  /usr/local/go/src/net/http/transport.go:1799 +0x152f

goroutine 1348 [select]:
net/http.(*persistConn).writeLoop(0xc000141440)
  /usr/local/go/src/net/http/transport.go:2444 +0xf0
created by net/http.(*Transport).dialConn in goroutine 1271
  /usr/local/go/src/net/http/transport.go:1800 +0x1585

goroutine 1437 [select]:
net/http.(*persistConn).writeLoop(0xc0009a5e60)
  /usr/local/go/src/net/http/transport.go:2444 +0xf0
created by net/http.(*Transport).dialConn in goroutine 1307
  /usr/local/go/src/net/http/transport.go:1800 +0x1585
gcsfuse exited with error: exit status 2
```

My setup is as follows
 - Main container image: `nvcr.io/nvidia/cuda:11.8.0-devel-ubuntu22.04`
 - Platform: `GKE v1.31.1-gke.1146000`
 - Gcsfuse `v1.5.0`

Dose anybody have some idea how I can debug it further?

**Comment by kislaykishore** [comment]
Could you double check the GCSFuse and GKE versions? The line numbers your error message align more with v2.4.0 than with 2.5.0.

**Comment by Tulsishah** [comment]
Hey @lewandowskim1988 ,

Can you please provide the steps to reproduce the issue?

Thanks,
Tulsi Shah

**Comment by gargnitingoogle** [comment]
> Gcsfuse v1.5.0

On GCSFuse version, there was no GCSFuse version 1.5.0. After 1.4.2, there was directly 2.0.0. 
Also given the error stack, 2.4.0 makes more sense than 2.5.0 which of the following line in stack:

/go/gcsfuse/internal/fs/fs.go:984 +0x46 , which is 
```go
    fs.mu.Unlock()
```
in v2.4.0 and 
```go
return parent.LookUpChild(ctx, childName)
```
in v2.5.0 . So it should be v2.4.0 . @lewandowskim1988 please confirm. Also, we need a way to better understand the issue, so any help in that would help. If you can help us recreate the issue, that'll be the best.

**Comment by raj-prince** [comment]
Hey @lewandowskim1988,

Thanks for reporting this issue!

Could you please help us in reproducing the issue by answering the below questions?
(a) Is this reproducible 100% or intermittent?
(b) Is your CI test bucket empty or contains some object in the start of the CI test?
(c) What all the operations do you perform as part of CI tests? Also, is any object shared across the test?
(d) Do you perform any operations externally to the bucket during the CI test execution?

Again, a small reproducer would be the best for us, if could provide. Otherwise, we will try to reproduce based on the response of the above questions.

Regards,
Prince Kumar.

**Comment by kislaykishore** [comment]
Closing as stale.

**Comment by raj-prince** [comment]
I am **able to reproduce this crash**.
  
It happens when **the application performs any operation on a file with name `\n`** present in the mounted directory. This is only possible when the mounting bucket contains an object ends with `\n`. E.g., `gs://bkt-with-invalid-file/a/\n`.

#### Steps to reproduce:
1. Create an object ends with `\n` in the bucket with the help of a local file `a.txt`. 
```sh
gcloud storage cp a.txt "gs://bkt-with-invalid-file/a/\n"
```
2. Mount gcsfuse as usual, let assume mounted directory is `/gcs`.
3. Perform any operation on the `\n` file via python (don't try with terminal as it appends `\` in the filename). E.g., performing stat with a simple python script (repro.py):
```python
import os

# Path with file name as '\n'
filepath = "/gcs/a/\n"
os.stat(filepath)
```
4. Output of executed python script in step-3. `Software caused connection abort: ` came because gcsfuse process crashed.
```text
Traceback (most recent call last):
  File "repro.py", line 5, in <module>
    os.stat(filepath)
ConnectionAbortedError: [Errno 103] Software caused connection abort: '/gcs/a/\n'
```
5. You can see the gcsfuse crash logs on the console.
```text
time="11/01/2025 07:58:08.794544" severity=TRACE message="fuse_debug: Op 0x00000008        connection.go:420] <- LookUpInode (parent 2, name \"\\n\", PID 609090)"
fatal error: sync: unlock of unlocked mutex

goroutine 196 [running]:
sync.fatal({0x1901b05?, 0xc000171830?})
        /home/princer_google_com/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.linux-amd64/src/runtime/panic.go:1031 +0x18
sync.(*Mutex).unlockSlow(0xc000c12c08, 0xffffffff)
        /home/princer_google_com/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.linux-amd64/src/sync/mutex.go:231 +0x35
sync.(*Mutex).Unlock(0xc000c08700?)
        /home/princer_google_com/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.linux-amd64/src/sync/mutex.go:225 +0x25
github.com/googlecloudplatform/gcsfuse/v2/internal/fs.(*fileSystem).lookUpLocalFileInode.func1()
        /home/princer_google_com/dev/gcsfuse/internal/fs/fs.go:1035 +0x46
panic({0x151c680?, 0xc000b90520?})
        /home/princer_google_com/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.linux-amd64/src/runtime/panic.go:785 +0x132
github.com/googlecloudplatform/gcsfuse/v2/internal/fs/inode.NewFileName({{0x0, 0x0}, {0xc000c12ef8, 0x2}}, {0x2957130, 0x0})
        /home/princer_google_com/dev/gcsfuse/internal/fs/inode/name.go:58 +0x108
github.com/googlecloudplatform/gcsfuse/v2/internal/fs.(*fileSystem).lookUpLocalFileInode(0xc000290300, {0x7c9d80cc35d8?, 0xc000b8e498?}, {0x2957130, 0x1?})
        /home/princer_google_com/dev/gcsfuse/internal/fs/fs.go:1040 +0x13f
github.com/googlecloudplatform/gcsfuse/v2/internal/fs.(*fileSystem).lookUpOrCreateChildInode(0xc000290300, {0x1c019f0, 0xc0001e5400}, {0x7c9d80cc35d8, 0xc000b8e498}, {0x2957130, 0x1})
```

#### Recommendation:
@lewandowskim1988 could you please check if your bucket contains any object name ends with `\n`? If yes, then please consider renaming those as a valid object name.

I have created a python script to find such objects (not via gcloud as terminal changes the regex):
```python
# Install google-cloud-storage module before running this python script: pip3 install google-cloud-storage

from google.cloud import storage

def find_gcs_objects_with_newline_suffix(bucket_name, prefix=None):
    try:
        client = storage.Client()
        bucket = client.bucket(bucket_name)
        objects_with_newline = []

        blobs = bucket.list_blobs(prefix=prefix)
        for blob in blobs:
            if blob.name.endswith('\\n'):
                objects_with_newline.append(f"gs://{bucket_name}/{blob.name}")

        return objects_with_newline

    except Exception as e:
        print(f"An error occurred: {e}")
        return []

if __name__ == "__main__":
    bucket_name = "princer-bkt-with-invalid-object" # Without gs://

    objects = find_gcs_objects_with_newline_suffix(bucket_name)

    if objects:
        print("Objects ending with '\\n':")
        for obj in objects:
            print(obj)
    else:
        print("No objects found ending with '\\n'.")
```

**Comment by lewandowskim1988** [comment]
Hello @raj-prince.

Thank you for your response and investigation.
Just to add more information about my case. The problem was not with files ending with `\n`. Currently we don't observe any problems and previous issues was probably some problems related to heavy development of our application.

**Comment by kislaykishore** [comment]
Related issue: https://github.com/GoogleCloudPlatform/gcsfuse/issues/2630

**Comment by Voziv** [comment]
For anyone landing here from googling the issue. This also comes up when you try and access a file with a newline. The file does not have to exist for this bug to come up.

EG: We have an nginx container that serves some files from a FUSE mount on GKE (gcs-fuse-csi-driver). If a web request goes to `/%0A` nginx will try to access a file with the newline and then our sidecar fails permanently until we restart the pod.

Haven't had the chance to test this new version yet (don't know how to get it on GKE), but I'm also looking at mitigating using our nginx configuration so external users cannot request newlines in filenames.

Hope it helps someone :)

**Comment by kislaykishore** [comment]
@Voziv The csi-driver shipped with GKE cluster version 1.32.1-gke.1753001 onwards comes with the fix.
