### ISSUE TITLE
Panic:  inode 1 is *inode.dirInode, wanted *inode.FileInode"

### ISSUE THREAD

**Issue by mihaiav** [GoogleCloudPlatform/gcsfuse#2753]
**Describe the issue**
Please provide a clear description of what you were trying to achieve along with the details of the flags that you passed.

I'm trying to mount a gcs bucket on Google Cloud Run. Sometimes it works but sometimes panics as below: 

```
2024-12-08 23:36:30.489
File system has been successfully mounted.
2024-12-08 23:37:13.447
{"seconds":1733693833,"nanos":448039747},"severity":"ERROR","message":"Panic: inode 1 is *inode.dirInode, wanted *inode.FileInode"} 
2024-12-08 23:37:13.448
{"seconds":1733693833,"nanos":448505546},"severity":"ERROR","message":"goroutine 13071 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:26 +0x5e\ngithub.com/googlecloudplatform/gcsfuse/v2/internal/logger.Fatal({0x17a06f1?, 0xc0002981c0?}, {0xc0006fbb78?, 0xc0006fbb4f?, 0xc0006fbba0?})\n\t/go/gcsfuse/internal/logger/logger.go:162 +0x25\ngithub.com/googlecloudplatform/gcsfuse/v2/internal/fs/wrappers.(*errorMapping).handlePanic(0x0?)\n\t/go/gcsfuse/internal/fs/wrappers/error_mapping.go:111 +0x45\npanic({0x1419fe0?, 0xc0009d66d0?})\n\t/usr/local/go/src/runtime/panic.go:785 +0x132\ngithub.com/googlecloudplatform/gcsfuse/v2/internal/fs.(*fileSystem).fileInodeOrDie(0x1aa8570?, 0x1)\n\t/go/gcsfuse/internal/fs/fs.go:1293 +0xcb\ngithub.com/googlecloudplatform/gcsfuse/v2/internal/fs.(*fileSystem).FlushFile(0xc0003fa2d0, {0x1aa8570?, 0xc00081c060?}, 0xc0008861e0)\n\t/go/gcsfuse/internal/fs/fs.go:2502 +0xb6\ngithub.com/googlecloudplatform/gcsfuse/v2/internal/fs/wrappers.(*errorMapping).FlushFile(0xc000a1a7b0, {0x1aa8570?, 0xc00081c060?}, 0x4e856f?)\n\t/go/gcsfuse/internal/fs/wrappers/error_mapping.go:323 +0x63\ngithub.com/googlecloudplatform/gcsfuse/v2/internal/fs/wrappers.(*monitoring).FlushFile.func1({0x1aa8570?, 0xc00081c060?})\n\t/go/gcsfuse/internal/fs/wrappers/monitoring.go:437 +0x36\ngithub.com/googlecloudplatform/gcsfuse/v2/internal/fs/wrappers.(*monitoring).invokeWrapped(0xc0005406e0, {0x1aa8570, 0xc0007f6d20}, {0x17a0fb2, 0x9}, 0xc00007bef0)\n\t/go/gcsfuse/internal/fs/wrappers/monitoring.go:341 +0x18a\ngithub.com/googlecloudplatform/gcsfuse/v2/internal/fs/wrappers.(*monitoring).FlushFile(0xc00070d090?, {0x1aa8570?, 0xc0007f6d20?}, 0xc0008643c0?)\n\t/go/gcsfuse/internal/fs/wrappers/monitoring.go:437 +0x45\ngithub.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc000540700, 0xc000740820, {0x1aa8570, 0xc0007f6d20}, {0x13e0ae0?, 0xc0008861e0})\n\t/tmp/build_gcsfuse_gopath1880646383/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20240607092844-7285af0d05b0/fuseutil/file_system.go:217 +0x36e\ncreated by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps in goroutine 75\n\t/tmp/build_gcsfuse_gopath1880646383/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20240607092844-7285af0d05b0/fuseutil/file_system.go:123 +0x1be\n"}

```
**Additional context**

**SLO:**
We strive to respond to all bug reports within 24 business hours provided the information mentioned above is included.

**Comment by ashmeenkaur** [comment]
Hello, thanks for reaching out. Could you please share GCSFuse version you are using?
It will be great if you could also share steps to reproduce the issue.

**Comment by mihaiav** [comment]
I'm trying to deploy and a wordpress docker installation with the `wp-content` directory sync/mounted on gcs. 
I seem to get this error all the time when wordpress is perhaps trying to read files. At this point I can say it never works(i.e. wordpress hangs as it can't read/write files) so I gave up of using GCSFuse as a solution. 
Below is the command I use to mount the directory. I also attached the Dockerfile and docker-entrypoint.sh

``gcsfuse --dir-mode 777 --file-mode 777 -o allow_other --key-file /usr/auth.json $my-bucket /var/www/html/wp-content``

[Dockerfile.txt](https://github.com/user-attachments/files/18057282/Dockerfile.txt)
[docker-entrypoint.sh.txt](https://github.com/user-attachments/files/18057301/docker-entrypoint.sh.txt)

**Comment by ashmeenkaur** [comment]
I am not able to repro the issue but I am suspecting that the issue is related to unsupported empty object in your bucket. Could you please check if there are any directories with empty names? 
Ref: https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#unsupported-object-names

This gcloud command should print any such objects:
```
gcloud storage ls -r gs://<your bucket name> | grep 'gs:\/\/.*\/\/'
```

**Comment by ankitaluthra1** [comment]
@mihaiav As suggested in last comment, GCSFuse does not support directories with empty names, can you please check if your bucket contains any such directory. In case there are no such directories, Could you please try one run using debug logs ON, this would help us understand the sequence of calls coming to GCSFuse. To turn On debug logs please use [--log-severity trace](https://cloud.google.com/storage/docs/cloud-storage-fuse/cli-options#:~:text=to%20highest%20severity%3A-,trace,-debug) command line parameter while running GCSFuse.

**Comment by gchux** [comment]
Similar issue here, GCSFuse version 2.7

> Note: running GCSFuse within GVISOR

```
time="07/01/2025 10:01:35.825628" severity=INFO message="Creating a new server...\n"
time="07/01/2025 10:01:35.826048" severity=INFO message="Set up root directory for bucket my-bucket"
time="07/01/2025 10:01:35.908333" severity=TRACE message="gcs: Req              0x0: <- ListObjects(\"\")"
time="07/01/2025 10:01:35.956240" severity=TRACE message="gcs: Req              0x0: -> ListObjects(\"\") (47.90274ms): OK"
time="07/01/2025 10:01:35.956442" severity=INFO message="Mounting file system \"my-bucket\"..."
time="07/01/2025 10:01:35.956519" severity=TRACE message="fuse_debug: Beginning the mounting kickoff process"
time="07/01/2025 10:01:35.956543" severity=TRACE message="fuse_debug: Parsing fuse file descriptor"
time="07/01/2025 10:01:35.956563" severity=TRACE message="fuse_debug: Preparing for direct mounting"
time="07/01/2025 10:01:35.956621" severity=TRACE message="fuse_debug: Successfully opened the /dev/fuse in blocking mode"
time="07/01/2025 10:01:35.956650" severity=TRACE message="fuse_debug: Starting the unix mounting"
time="07/01/2025 10:01:35.956703" severity=TRACE message="fuse_debug: Unix mounting completed successfully"
time="07/01/2025 10:01:35.956718" severity=TRACE message="fuse_debug: Completed the mounting kickoff process"
time="07/01/2025 10:01:35.956729" severity=TRACE message="fuse_debug: Creating a connection object"
time="07/01/2025 10:01:35.958101" severity=TRACE message="fuse_debug: Op 0x00000002        connection.go:420] <- init"
time="07/01/2025 10:01:35.958141" severity=TRACE message="fuse_debug: Op 0x00000002        connection.go:513] -> OK ()"
time="07/01/2025 10:01:35.958186" severity=TRACE message="fuse_debug: Successfully created the connection"
time="07/01/2025 10:01:35.958212" severity=TRACE message="fuse_debug: Waiting for mounting process to complete"
time="07/01/2025 10:01:35.958228" severity=INFO message="File system has been successfully mounted."
time="07/01/2025 10:01:47.043397" severity=TRACE message="fuse_debug: Op 0x00000004        connection.go:420] <- GetInodeAttributes (inode 1, PID 456)"
time="07/01/2025 10:01:47.043608" severity=TRACE message="fuse_debug: Op 0x00000004        connection.go:513] -> OK ()"
time="07/01/2025 10:01:47.044034" severity=TRACE message="fuse_debug: Op 0x00000006        connection.go:420] <- OpenDir (inode 1, PID 456)"
time="07/01/2025 10:01:47.044145" severity=TRACE message="fuse_debug: Op 0x00000006        connection.go:513] -> OK ()"
time="07/01/2025 10:01:47.044272" severity=TRACE message="fuse_debug: Op 0x00000008        connection.go:420] <- ReadDir (inode 1, PID 456)"
time="07/01/2025 10:01:47.044426" severity=TRACE message="gcs: Req              0x1: <- ListObjects(\"\")"
time="07/01/2025 10:01:47.073535" severity=TRACE message="gcs: Req              0x1: -> ListObjects(\"\") (29.120813ms): OK"
time="07/01/2025 10:01:47.073633" severity=TRACE message="fuse_debug: Op 0x00000008        connection.go:513] -> OK ()"
time="07/01/2025 10:01:47.073797" severity=TRACE message="fuse_debug: Op 0x0000000a        connection.go:420] <- LookUpInode (parent 1, name \"chux-testing\", PID 456)"
time="07/01/2025 10:01:47.074045" severity=TRACE message="fuse_debug: Op 0x0000000a        connection.go:513] -> OK (inode 2)"
time="07/01/2025 10:01:47.074133" severity=TRACE message="fuse_debug: Op 0x0000000c        connection.go:420] <- GetInodeAttributes (inode 2, PID 456)"
time="07/01/2025 10:01:47.074202" severity=TRACE message="fuse_debug: Op 0x0000000c        connection.go:513] -> OK ()"
time="07/01/2025 10:01:47.074346" severity=TRACE message="fuse_debug: Op 0x0000000e        connection.go:420] <- ReadDir (inode 1, PID 456)"
time="07/01/2025 10:01:47.074420" severity=TRACE message="fuse_debug: Op 0x0000000e        connection.go:513] -> OK ()"
time="07/01/2025 10:01:47.074531" severity=TRACE message="fuse_debug: Op 0x00000010        connection.go:420] <- FlushFile (inode 1, PID 456)"
time="07/01/2025 10:01:47.074582" severity=TRACE message="fuse_debug: Op 0x00000012        connection.go:420] <- ReleaseDirHandle (PID 456)"
time="07/01/2025 10:01:47.075278" severity=ERROR message="Panic: inode 1 is *inode.dirInode, wanted *inode.FileInode"
time="07/01/2025 10:01:47.076995" severity=ERROR message="goroutine 81 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:26 +0x5e\ngithub.com/googlecloudplatform/gcsfuse/v2/internal/logger.Fatal({0x17a06f1?, 0xc0007ac8c0?}, {0xc00059eb78?, 0xc00059eb4f?, 0xc00059eba0?})\n\t/go/gcsfuse/internal/logger/logger.go:162 +0x25\ngithub.com/googlecloudplatform/gcsfuse/v2/internal/fs/wrappers.(*errorMapping).handlePanic(0x0?)\n\t/go/gcsfuse/internal/fs/wrappers/error_mapping.go:111 +0x45\npanic({0x1419fe0?, 0xc000597260?})\n\t/usr/local/go/src/runtime/panic.go:785 +0x132\ngithub.com/googlecloudplatform/gcsfuse/v2/internal/fs.(*fileSystem).fileInodeOrDi
e(0x1aa8570?, 0x1)\n\t/go/gcsfuse/internal/fs/fs.go:1293 +0xcb\ngithub.com/googlecloudplatform/gcsfuse/v2/internal/fs.(*fileSystem).FlushFile(0xc0008480f0, {0x1aa8570?, 0xc00084a780?}, 0xc0009bcb20)\n\t/go/gcsfuse/internal/fs/
fs.go:2502 +0xb6\ngithub.com/googlecloudplatform/gcsfuse/v2/internal/fs/wrappers.(*errorMapping).FlushFile(0xc000596320, {0x1aa8570?, 0xc00084a780?}, 0x4e856f?)\n\t/go/gcsfuse/internal/fs/wrappers/error_mapping.go:323 +0x63\ng
ithub.com/googlecloudplatform/gcsfuse/v2/internal/fs/wrappers.(*monitoring).FlushFile.func1({0x1aa8570?, 0xc00084a780?})\n\t/go/gcsfuse/internal/fs/wrappers/monitoring.go:437 +0x36\ngithub.com/googlecloudplatform/gcsfuse/v2/in
ternal/fs/wrappers.(*monitoring).invokeWrapped(0xc0000660e0, {0x1aa8570, 0xc00095a870}, {0x17a0fb2, 0x9}, 0xc00002cef0)\n\t/go/gcsfuse/internal/fs/wrappers/monitoring.go:341 +0x18a\ngithub.com/googlecloudplatform/gcsfuse/v2/in
ternal/fs/wrappers.(*monitoring).FlushFile(0x0?, {0x1aa8570?, 0xc00095a870?}, 0x0?)\n\t/go/gcsfuse/internal/fs/wrappers/monitoring.go:437 +0x45\ngithub.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc000066100, 0xc00
052a5b0, {0x1aa8570, 0xc00095a870}, {0x13e0ae0?, 0xc0009bcb20})\n\t/tmp/build_gcsfuse_gopath1880646383/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20240607092844-7285af0d05b0/fuseutil/file_system.go:217 +0x36e\ncreated by github.co
m/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps in goroutine 30\n\t/tmp/build_gcsfuse_gopath1880646383/pkg/mod/github.com/jacobsa/fuse@v0.0.0-20240607092844-7285af0d05b0/fuseutil/file_system.go:123 +0x1be\n"
```

**Comment by raj-prince** [comment]
Thanks @gchux for the logs!

Very strange, file-specific operation (FlushFile) on the root directory Inode.

Looking into this.

**Comment by gchux** [comment]
exactly, in that sample I was just listing the directory where the Bucker is mounted.

Unclear why GCSFuse is expecting a file instead of a directory...

**Comment by raj-prince** [comment]
Hi @mihaiav,

**Issue:** GCSFuse crashes while listing over a directory.

**Why crash?** It is because of an unexpected `FlushFile` for a directory inode at the end of listing. GCSFuse expects `OpenDir`, `ReadDir`, and `ReleaseDirHandle` for directory listing, no `FlushFile`.

**Why does the FlushFile call occur?:** It's unclear, but this behavior only occurs when the Cloud Run container is deployed `--execution-environment=gen1`. This environment uses an old kernel version (4.4.0, released in Jan 2016) and [gVisor](https://github.com/google/gvisor). The issue could be due to the old kernel, gVisor, or a combination of both.

**Fix/workaround:** Use `--execution-environment=gen2` when deploying the Cloud Run container.

If gen1 is unavoidable, @gchux created a [patch](https://github.com/gchux/cloud-run-tcpdump/blob/main/gcsfuse/patch/internal/fs/fs.go) (by removing the panic and making `FlushFile` a no-op for directory Inode), which seems to be working. However, GCSFuse officially does not support this old Linux version.

Thanks!

**Comment by gchux** [comment]
thanks @raj-prince !

Added a quick README to clarify how the patch works:
- https://github.com/gchux/cloud-run-tcpdump/tree/main/gcsfuse

I think we are good to go with this issue.
