### ISSUE TITLE
ImportError: No module named 'fuse'

### ISSUE THREAD

**Issue by anshoomehra** [GoogleCloudPlatform/gcsfuse#331]
Trying to mount "Google Cloud Storage Bucket" to "Google Cloud > AI > Notebook Instance"

**Command**: gcsfuse gs://aiml_dev aiml_dev

**Error**:
Traceback (most recent call last):
  File "/usr/local/bin/gcsfuse", line 7, in <module>
    from gcsfs.cli.gcsfuse import main
  File "/usr/local/lib/python3.5/dist-packages/gcsfs/cli/gcsfuse.py", line 3, in <module>
    from fuse import FUSE
**_ImportError: No module named 'fuse'_**

**Supporting Details**: 

**OS**: SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
**Release**: Codename: stretch

**Install**: https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md
**1. Tried installing via apt-get install**
Output: 
jupyter@anshoo-jy-tf:~/anmehra$ sudo apt-get install gcsfuse
Reading package lists... Done
Building dependency tree
Reading state information... Done
gcsfuse is already the newest version (0.27.0).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**2. Later realized that I should have followed dpkg path to install, tried reinstalling the same 
<img width="740" alt="Screen Shot 2019-06-07 at 1 19 34 PM" src="https://user-images.githubusercontent.com/24396120/59121722-ec6f7200-8926-11e9-863f-4474db8fed27.png">
install via sudo dkpg**
Output:
jupyter@anshoo-jy-tf:~/anmehra$ sudo dpkg --install gcsfuse_0.27.0_amd64.deb
(Reading database ... 85403 files and directories currently installed.)
Preparing to unpack gcsfuse_0.27.0_amd64.deb ...
Unpacking gcsfuse (0.27.0) over (0.27.0) ...
Setting up gcsfuse (0.27.0) ...

**Comment by darkvertex** [comment]
gcsfuse (this repo) is written in Go, not Python. You appear to have installed:
https://github.com/dask/gcsfs/blob/master/gcsfs/cli/gcsfuse.py

Or maybe you did install the proper gcsfuse system package _but_ also installed the [gcsfs Python module](https://github.com/dask/gcsfs) and their "gcsfuse" executable took precendence in the PATH. (Try `echo $PATH` and see.)

**Comment by bjornleffler** [comment]
Have you installed the fuse package for Python?
apt-get install python-fuse

From apt-cache search fuse | grep python:
python-fuse - Python bindings for FUSE (Filesystems in USErspace)

**Comment by er214** [comment]
I've just had the same issue on a predefined deep learning instance - that comes preinstalled with a load of software. This must have had the python version also installed. 

You can work around just by called the relevant installation directly. Find them both using `whereis gcsfuse`, and then using the full path to the non-python version (in my case `/usr/bin/gcsfuse`).

**Comment by achbogga** [comment]
Yes, in my case the pre-installed version was sitting at /usr/local/bin/. I installed right version with package manager after adding the relevant source.
`
export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install gcsfuse
`
Then, to tell your system to use the right version just put the following snippet in your ~/.bashrc

 ` gcsfuse() {
          /usr/bin/gcsfuse "$@"
  }
`
Now execute 

`exec bash`

and voila!

**Comment by jolastar** [comment]
I also find that there is a pre-installed (Python) executable under `/usr/local/bin/`, overriding the Go version installed which is located at `/usr/bin/` when installed according to the instructions.

So I just use explicitly `/usr/bin/gcsfuse`.

I notice two practical differences between this Go version and the command provided by the `gcsfs` Python package:
* The Go version runs in the background by default, no need for `--background`
* You need `--implicit-dirs` option to see implicit directories (see issue #303 for example)

In any case, the Python import error is not an issue of the Go program so this issue should be closed, shouldn't it?
