### ISSUE TITLE
sqlite3.OperationalError: disk I/O error

### ISSUE THREAD

**Issue by skhaz** [GoogleCloudPlatform/gcsfuse#480]
I am using a project that uses SQLite and when I try to run this software on a gcsfuse mounted dir I got this error:

```
gphotos-sync .
12-27 01:36:48 WARNING  gphotos-sync 2.14.2 2020-12-27 01:36:47.964893 
12-27 01:36:53 ERROR    
Process failed. 
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gphotos/Main.py", line 417, in main
    self.setup(args, db_path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gphotos/Main.py", line 263, in setup
    self.data_store = LocalData(db_path, args.flush_index)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gphotos/LocalData.py", line 53, in __init__
    self.clean_db()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/gphotos/LocalData.py", line 105, in clean_db
    self.cur.executescript(qry)
sqlite3.OperationalError: disk I/O error
```

Any clues?

**Comment by lezh** [comment]
Probably SQLite used some FS operations that Gcsfuse does not support. 
https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/semantics.md#surprising-behaviors
