### ISSUE TITLE
ACLs enabled leads to nil pointer dereference

### ISSUE THREAD

**Issue by logston** [GoogleCloudPlatform/gcsfuse#981]
**Describe the bug**

Upon attempting to mount a bucket with "Fine-grained: Object-level ACLs enabled" access control permissions, the following error is reached:

```
$ gcsfuse --debug_fuse --debug_fs --debug_gcs --debug_http --foreground <redact> /bucket 
2023/03/02 00:16:45.779563 Start gcsfuse/0.42.1 (Go version go1.19.5) for app "" using mount point: /bucket
2023/03/02 00:16:45.779673 Opening GCS connection...
2023/03/02 00:16:45.785482 Creating a mount at "/bucket"
2023/03/02 00:16:45.786024 Creating a new server...
2023/03/02 00:16:45.786048 Set up root directory for bucket <redact>
gcs: 2023/03/02 00:16:45.880729 Req              0x0: <- ListObjects("")
gcs: 2023/03/02 00:16:45.945337 Req              0x0: -> ListObjects("") (64.601494ms): OK
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa889ff]

goroutine 1 [running]:
github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil.convertACLRuleToObjectAccessControl(...)
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil/object_attrs.go:48
github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil.ObjectAttrsToBucketObject(0xc0002941e0)
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/storage/storageutil/object_attrs.go:58 +0x5ff
github.com/googlecloudplatform/gcsfuse/internal/storage.(*bucketHandle).ListObjects(0xc00034a8d0, {0x11648d0, 0xc0001300c8}, 0xc000758410)
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/storage/bucket_handle.go:245 +0x2aa
github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs.(*debugBucket).ListObjects(0xc00048a460, {0x11648d0, 0xc0001300c8}, 0xc000758410)
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/debug_bucket.go:207 +0x16b
github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/gcscaching.(*fastStatBucket).ListObjects(0xc00048c3c0, {0x11648d0?, 0xc0001300c8?}, 0xc0007cf101?)
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/jacobsa/gcloud/gcs/gcscaching/fast_stat_bucket.go:219 +0x34
github.com/googlecloudplatform/gcsfuse/internal/gcsx.(*bucketManager).SetUpBucket(0xc00049c480, {0x11648d0, 0xc0001300c8}, {0x7fff26f3beb9?, 0x70?})
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/gcsx/bucket_manager.go:248 +0x5c4
github.com/googlecloudplatform/gcsfuse/internal/fs.NewFileSystem({0x11648d0, 0xc0001300c8}, 0xc00065f5e8)
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/fs/fs.go:167 +0x47a
github.com/googlecloudplatform/gcsfuse/internal/fs.NewServer({0x11648d0?, 0xc0001300c8?}, 0xc0007cf5e8)
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/internal/fs/server.go:28 +0x2f
main.mountWithConn({0x11648d0, 0xc0001300c8}, {0x7fff26f3beb9, 0x23}, {0x7fff26f3bedd, 0x7}, 0xc00013a160, 0x50?, {0x1159d80, 0xc0000140b8}, ...)
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/mount.go:122 +0x4ba
main.mountWithArgs({0x7fff26f3beb9, 0x23}, {0x7fff26f3bedd, 0x7}, 0xc00013a160, 0x6?)
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:205 +0x2d2
main.runCLIApp(0xc00063f8f8?)
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:369 +0xf25
main.run.func1(0x1?)
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:404 +0x25
github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.HandleAction({0xcd6640?, 0xc000070080?}, 0xc0005f6000?)
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:526 +0x50
github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli.(*App).Run(0xc0005f6000, {0xc00012a000, 0x8, 0x8})
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/vendor/github.com/urfave/cli/app.go:286 +0x7ca
main.run()
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:408 +0xcb
main.main()
        /tmp/build_gcsfuse_gopath3986937209/src/github.com/googlecloudplatform/gcsfuse/main.go:426 +0x4a
$
```

```
$ gcsfuse -v 
gcsfuse version 0.42.1 (Go version go1.19.5)
```

<img width="978" alt="Screenshot 2023-03-01 at 4 19 45 PM" src="https://user-images.githubusercontent.com/2641765/222297737-72986304-ab31-4483-9c5f-79b53fde19e9.png">

**System:**
 - OS: Mounting from a pod created with `debian:buster` image. 
 - Platform: Kubernetes
 - Version: 0.42.1

When I changed the bucket permissions to "Uniform: No object-level ACLs enabled", the bucket mounts just fine:

```
$ gcsfuse --debug_fuse --debug_fs --debug_gcs --debug_http --foreground <redact> /bucket 
2023/03/02 00:25:02.976509 Start gcsfuse/0.42.1 (Go version go1.19.5) for app "" using mount point: /bucket
2023/03/02 00:25:02.976629 Opening GCS connection...
2023/03/02 00:25:02.983243 Creating a mount at "/bucket"
2023/03/02 00:25:02.984119 Creating a new server...
2023/03/02 00:25:02.984156 Set up root directory for bucket <redact>
gcs: 2023/03/02 00:25:03.094454 Req              0x0: <- ListObjects("")
gcs: 2023/03/02 00:25:03.143518 Req              0x0: -> ListObjects("") (49.059806ms): OK
2023/03/02 00:25:03.143599 Mounting file system "<redact>"...
fuse_debug: 2023/03/02 00:25:03.143668 Beginning the mounting kickoff process
fuse_debug: 2023/03/02 00:25:03.143681 Parsing fuse file descriptor
fuse_debug: 2023/03/02 00:25:03.143687 Preparing for direct mounting
fuse_debug: 2023/03/02 00:25:03.143775 Successfully opened the /dev/fuse in blocking mode
fuse_debug: 2023/03/02 00:25:03.143798 Starting the unix mounting
fuse_debug: 2023/03/02 00:25:03.143836 Directmount failed. Trying fallback.
fuse_debug: 2023/03/02 00:25:03.143993 Creating a socket pair
fuse_debug: 2023/03/02 00:25:03.144050 Creating files to wrap the sockets
fuse_debug: 2023/03/02 00:25:03.144066 Starting fusermount/os mount
fuse_debug: 2023/03/02 00:25:03.146819 Wrapping socket pair in a connection
fuse_debug: 2023/03/02 00:25:03.146967 Checking that we have a unix domain socket
fuse_debug: 2023/03/02 00:25:03.146976 Read a message from socket
fuse_debug: 2023/03/02 00:25:03.147001 Successfully read the socket message.
fuse_debug: 2023/03/02 00:25:03.147009 Converting FD into os.File
fuse_debug: 2023/03/02 00:25:03.147058 Completed the mounting kickoff process
fuse_debug: 2023/03/02 00:25:03.147064 Creating a connection object
fuse_debug: 2023/03/02 00:25:03.147254 Op 0x00000002        connection.go:416] <- init
fuse_debug: 2023/03/02 00:25:03.147284 Op 0x00000002        connection.go:498] -> OK ()
fuse_debug: 2023/03/02 00:25:03.147309 Successfully created the connection
fuse_debug: 2023/03/02 00:25:03.147341 Waiting for mounting process to complete
2023/03/02 00:25:03.147349 File system has been successfully mounted.
```

**Comment by Tulsishah** [comment]
Thanks, @logston, for the information. Currently, we are working on it. We will update you once it gets fixed. 
In the mean time, you can pass --enable-storage-client-library=false flag.

**Comment by manvindar-telus** [comment]
I have the same issue.

**Comment by sethiay** [comment]
The fix for this issue has been released in the latest GCSFuse release i.e. [v0.42.2](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.42.2). With GCSFuse v0.42.2, you can skip passing --enable-storage-client-library=false flag.
Marking this issue as closed. Please feel free to re-open in case you face the same issue again.

Thanks for your patience !
